# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestReport():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_report(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1382, 744)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.NAME, "username").send_keys("user")
    self.driver.find_element(By.NAME, "password").send_keys("user@123")
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").click()
    element = self.driver.find_element(By.NAME, "username")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "username").send_keys("ngo")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").click()
    element = self.driver.find_element(By.NAME, "password")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.NAME, "password").send_keys("user@123")
    self.driver.find_element(By.LINK_TEXT, "Report").click()
    self.driver.find_element(By.LINK_TEXT, "View Details").click()
    self.driver.execute_script("window.scrollTo(0,612)")
    self.driver.find_element(By.CSS_SELECTOR, ".mb-3:nth-child(8)").click()
    self.driver.find_element(By.LINK_TEXT, "Accept").click()
    self.driver.find_element(By.LINK_TEXT, "View Details").click()
    self.driver.execute_script("window.scrollTo(0,408)")
    self.driver.find_element(By.LINK_TEXT, "Accept").click()
    self.driver.find_element(By.LINK_TEXT, "View Details").click()
    self.driver.execute_script("window.scrollTo(0,102)")
    self.driver.find_element(By.LINK_TEXT, "Accept").click()
    self.driver.find_element(By.LINK_TEXT, "View Details").click()
    self.driver.execute_script("window.scrollTo(0,510)")
    self.driver.find_element(By.LINK_TEXT, "ngo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Report").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6:nth-child(2) .btn").click()
    self.driver.execute_script("window.scrollTo(0,408)")
    self.driver.find_element(By.LINK_TEXT, "Report").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6:nth-child(4) .btn").click()
    self.driver.execute_script("window.scrollTo(0,204)")
    self.driver.find_element(By.LINK_TEXT, "Report").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.NAME, "username").send_keys("user")
    self.driver.find_element(By.NAME, "password").send_keys("user@123")
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").click()
    element = self.driver.find_element(By.NAME, "username")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "username").send_keys("volunteer")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Report").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6:nth-child(4) .btn").click()
    self.driver.find_element(By.LINK_TEXT, "Accept").click()
    self.driver.find_element(By.LINK_TEXT, "volunteer").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
  
