# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestProfileandleaderboard():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_profileandleaderboard(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1382, 744)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.NAME, "username").send_keys("user")
    self.driver.find_element(By.NAME, "password").send_keys("user@123")
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").click()
    element = self.driver.find_element(By.NAME, "username")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").click()
    element = self.driver.find_element(By.NAME, "password")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.NAME, "password").send_keys("user@123")
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.NAME, "profile_pic").click()
    self.driver.find_element(By.NAME, "profile_pic").send_keys("C:\\fakepath\\MM.png")
    self.driver.find_element(By.NAME, "phone").click()
    self.driver.find_element(By.NAME, "phone").send_keys("01577142710")
    self.driver.find_element(By.NAME, "address").click()
    self.driver.find_element(By.NAME, "address").send_keys("Mohammadpur, Dhaka-1207")
    self.driver.find_element(By.NAME, "bio").click()
    self.driver.find_element(By.NAME, "bio").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.NAME, "profile_pic").click()
    self.driver.find_element(By.NAME, "profile_pic").send_keys("C:\\fakepath\\MM.png")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Leaderboard").click()
    self.driver.find_element(By.CSS_SELECTOR, ".section-spacer > .container").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-primary:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-warning:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-success:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.NAME, "username").send_keys("user")
    self.driver.find_element(By.NAME, "password").send_keys("user@123")
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").click()
    element = self.driver.find_element(By.NAME, "username")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "username").send_keys("ngo")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").click()
    element = self.driver.find_element(By.NAME, "password")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.NAME, "password").send_keys("user@123")
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.NAME, "profile_pic").click()
    self.driver.find_element(By.NAME, "profile_pic").send_keys("C:\\fakepath\\MM.png")
    self.driver.find_element(By.NAME, "phone").click()
    self.driver.find_element(By.NAME, "phone").send_keys("01577142710")
    self.driver.find_element(By.NAME, "organization_name").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.NAME, "username").send_keys("user")
    self.driver.find_element(By.NAME, "password").send_keys("user@123")
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").click()
    element = self.driver.find_element(By.NAME, "username")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "username").send_keys("volunteer")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").click()
    element = self.driver.find_element(By.NAME, "password")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.NAME, "password").send_keys("user@123")
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-8 > .glass").click()
    self.driver.find_element(By.NAME, "profile_pic").click()
    self.driver.find_element(By.NAME, "profile_pic").send_keys("C:\\fakepath\\MM.png")
    self.driver.find_element(By.NAME, "phone").click()
    self.driver.find_element(By.NAME, "phone").send_keys("01577142710")
    self.driver.find_element(By.NAME, "address").click()
    self.driver.find_element(By.NAME, "address").send_keys("Mohammadpur")
    self.driver.find_element(By.NAME, "bio").click()
    self.driver.find_element(By.NAME, "bio").send_keys("I am a volunteer")
    self.driver.find_element(By.NAME, "skills").click()
    self.driver.find_element(By.NAME, "skills").send_keys("First AID")
    self.driver.find_element(By.NAME, "certificate").click()
    self.driver.find_element(By.NAME, "certificate").send_keys("C:\\fakepath\\logo.jpg")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".skills-display").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "View Certificate").click()
    self.vars["win5373"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win5373"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
  
