# Generated by Django 5.2.5 on 2025-09-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_role_customuser_is_ngo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_ngo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_volunteer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('volunteer', 'Volunteer'), ('ngo', 'NGO')], default='user', max_length=20),
        ),
    ]
