# Generated by Django 5.2.5 on 2025-10-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_certificate_customuser_organization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
