# Generated by Django 5.2.5 on 2025-09-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_report_accepted_by_report_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
