# Generated by Django 5.2.5 on 2025-09-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_report_latitude_report_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reports/videos/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
