# Generated by Django 5.2.5 on 2025-10-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_report_video_alter_report_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reports/photos/'),
        ),
    ]
