# Generated by Django 5.2.5 on 2025-08-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_report_location_report_location_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location_lng',
        ),
        migrations.RemoveField(
            model_name='report',
            name='media',
        ),
        migrations.RemoveField(
            model_name='report',
            name='proof_count',
        ),
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
